# Generated by Django 4.2.11 on 2024-04-12 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userprofile_department_userprofile_employee_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('Sales Advisor', 'Sales Advisor'), ('Manager', 'Manager')], default='Sales Advisor', max_length=50),
        ),
    ]
