# Generated by Django 4.2.11 on 2024-04-13 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='shift_person',
        ),
    ]
