# Generated by Django 4.2.11 on 2024-04-13 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_remove_shift_shift_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='shift_name',
        ),
        migrations.AddField(
            model_name='shift',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
