# Generated by Django 4.2.11 on 2024-04-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_remove_shift_shift_name_shift_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
