# Generated by Django 4.2.11 on 2024-04-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_request_approval_status_receivergroup_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivergroup',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
    ]
