# Generated by Django 4.2.11 on 2024-04-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_receivergroup_is_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='audio',
            field=models.FileField(null=True, upload_to='assets/', verbose_name=''),
        ),
    ]
